#pragma once

/*
IMPLEMENT PIXEL PERFECT COLLIDER!

STORE A LIST OF 1 AND 0 THAT TELL WHETHER EACH PIXEL OF THE AREA OF THE OBJECT HAS COLLISION.

CHECK IF PLAYER OVERLAPS A 1 OR 0 AND APPLY SOME FORCE.

*/